SELECT * FROM [LUIS-SAB-HP-ENV].[AdvancedInc].[dbo].[USUARIOS]
UNION
SELECT * FROM [FROSTRITE-LAPTO].[AdvancedInc].[dbo].[USUARIOS]
/*
UNION
SELECT * FROM [DESKTOP-34N0LII].[AdvancedInc].[dbo].[USUARIOS]
UNION
SELECT * FROM [DESKTOP-0RHBA78].[AdvancedInc].[dbo].[USUARIOS]
*/




/*
CREATE PARTITION FUNCTION codSedePartition (int)  
AS RANGE LEFT FOR VALUES (1, 2, 3); 
*/